# string values should be either 3 characters or less (a patch name) or be delimited like so:
# "Small Text|BIG". The small text will be displayed above the 3 big characters as a header, although they also shouldn'r be that long. 6-10 characters is a good number.
0 = "MVMT 1|000"
1 = "MVMT 1|001"
2 = "MVMT 1|002"
3 = "MVMT 1|003"
4 = "MVMT 2|001"
5 = "MVMT 2|002"
6 = "MVMT 2|003"
7 = "MVMT 3|001"
8 = "MVMT 3|002"
9 = "MVMT 3|003"
10 = "1.0"
11 = "1.1"
12 = "1.2"
13 = "1.3"
14 = "2.1"
15 = "2.2"
16 = "2.3"
100 = "SC"
101 = "WRM"